"""Burn Index — anonymous community percentiles of agent EFFICIENCY.

Volume leaderboards get gamed (people flex token burn; tops fill with fakes).
The Burn Index ranks nothing anyone would want to inflate: it compares
efficiency — fixed overhead per call, night share, idle heartbeats, failure
burn, cache utilization. Spend appears only as a coarse band.

Flow, zero infrastructure, consent by action:
1. `agentburn --submit` prints the exact anonymized payload, then a GitHub
   issue URL with it prefilled. YOU open the link and click submit (or don't).
2. A weekly Action aggregates `burn-index` issues into data/burn-index.json
   (plausibility bounds filter junk; n<5 → "insufficient").
3. `agentburn rank` fetches that public JSON and tells you where you stand:
   "overhead worse than ~75% of N submissions."
"""

from __future__ import annotations

import json
import os
import urllib.parse
import urllib.request

REPO = "Socialpranker/agentburn"
INDEX_URL = f"https://raw.githubusercontent.com/{REPO}/main/data/burn-index.json"
SCHEMA = 1

SPEND_BANDS = ((10, "<$10"), (50, "$10-50"), (200, "$50-200"), (1000, "$200-1000"), (float("inf"), "$1000+"))

# metric → (label, lower_is_better)
METRICS = {
    "overhead_cli": ("input tokens per call · cli", True),
    "overhead_gateway_max": ("input tokens per call · heaviest gateway", True),
    "night_share": ("share of spend at night", True),
    "idle_heartbeat_share": ("heartbeat runs that did nothing", True),
    "failure_share": ("share of spend burned in failed runs", True),
    "cache_read_share": ("cache-read share of input volume", False),
}

# plausibility bounds for aggregation (drop obvious junk/gaming)
BOUNDS = {
    "overhead_cli": (50, 400_000),
    "overhead_gateway_max": (50, 400_000),
    "night_share": (0.0, 1.0),
    "idle_heartbeat_share": (0.0, 1.0),
    "failure_share": (0.0, 1.0),
    "cache_read_share": (0.0, 1.0),
}


def spend_band(monthly: float | None) -> str:
    if monthly is None:
        return "unknown"
    for limit, label in SPEND_BANDS:
        if monthly < limit:
            return label
    return "$1000+"


def build_metrics(analyses: list, breps: list) -> dict:
    """Anonymized-by-construction: shares, ratios and a coarse band only."""
    agents = sorted({a.agent.split(" ·")[0] for a in analyses})
    out = {"schema": SCHEMA, "agents": agents, "window_days": analyses[0].days if analyses else None}

    oh_cli, oh_gw = [], []
    cost_total = night = 0.0
    cache_read = inputs = 0
    monthly = 0.0
    monthly_known = False
    for a in analyses:
        for src, v in a.overhead_per_call.items():
            if src == "cli":
                oh_cli.append(v)
            elif src.startswith("gateway:"):
                oh_gw.append(v)
        if a.total.cost_known:
            cost_total += a.total.cost
            night += a.night.cost
        cache_read += a.total.cache_read_tokens
        inputs += a.total.input_tokens + a.total.cache_read_tokens
        if a.monthly_projection is not None:
            monthly += a.monthly_projection
            monthly_known = True

    idle_n = idle_d = 0
    fail_cost = 0.0
    for r in breps:
        n, total, _ = r.idle_heartbeats
        idle_n += n
        idle_d += total
        if r.failure_cost[1]:
            fail_cost += r.failure_cost[1]

    if oh_cli:
        out["overhead_cli"] = int(sum(oh_cli) / len(oh_cli))
    if oh_gw:
        out["overhead_gateway_max"] = int(max(oh_gw))
    if cost_total > 0:
        out["night_share"] = round(night / cost_total, 3)
        out["failure_share"] = round(min(1.0, fail_cost / cost_total), 3)
    if idle_d > 0:
        out["idle_heartbeat_share"] = round(idle_n / idle_d, 3)
    if inputs > 0:
        out["cache_read_share"] = round(cache_read / inputs, 3)
    out["spend_band"] = spend_band(monthly if monthly_known else None)
    return out


def submit_url(metrics: dict) -> str:
    body = (
        "Anonymous Burn Index submission (generated by `agentburn --submit`; "
        "review the numbers — they contain no titles, paths or content):\n\n"
        "```json\n" + json.dumps(metrics, indent=1) + "\n```\n"
    )
    qs = urllib.parse.urlencode({
        "title": f"burn-index: {metrics.get('spend_band', 'unknown')} · {'+'.join(metrics.get('agents', []))}",
        "labels": "burn-index",
        "body": body,
    })
    return f"https://github.com/{REPO}/issues/new?{qs}"


def load_index(source: str = INDEX_URL, timeout: int = 15) -> dict:
    if os.path.exists(source):
        with open(source, "r", encoding="utf-8") as f:
            return json.load(f)
    req = urllib.request.Request(source, headers={"user-agent": "agentburn-rank"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as res:
            return json.loads(res.read().decode("utf-8", errors="replace"))
    except Exception as e:  # noqa: BLE001
        raise RuntimeError(
            f"burn index unavailable ({e}) — pass --benchmark-file FILE or try later."
        ) from None


def _band_for(value: float, q: dict, lower_better: bool):
    """→ human position vs published quantiles p25/p50/p75/p90."""
    pairs = [(25, q.get("p25")), (50, q.get("p50")), (75, q.get("p75")), (90, q.get("p90"))]
    pairs = [(p, v) for p, v in pairs if v is not None]
    if not pairs:
        return None
    worse_than = 0
    for p, v in pairs:
        if (value >= v) if lower_better else (value <= v):
            worse_than = p
    return worse_than


def rank_against(metrics: dict, index: dict) -> list:
    rows = []
    agg = index.get("metrics") or {}
    for key, (label, lower_better) in METRICS.items():
        mine = metrics.get(key)
        q = agg.get(key)
        if mine is None or not q or q.get("n", 0) < 5:
            continue
        worse = _band_for(mine, q, lower_better)
        rows.append({
            "metric": key,
            "label": label,
            "value": mine,
            "median": q.get("p50"),
            "worse_than_pct": worse,
            "lower_is_better": lower_better,
            "n": q.get("n"),
        })
    return rows


def render_rank(rows: list, index: dict, color: bool = True) -> str:
    b = (lambda s: f"\033[1m{s}\033[0m") if color else (lambda s: s)
    dim = (lambda s: f"\033[2m{s}\033[0m") if color else (lambda s: s)
    red = (lambda s: f"\033[31m{s}\033[0m") if color else (lambda s: s)
    green = (lambda s: f"\033[32m{s}\033[0m") if color else (lambda s: s)
    out = ["", b("📊 agentburn rank — you vs the Burn Index")]
    out.append(dim("   anonymous community percentiles of EFFICIENCY — nothing here rewards burning more"))
    out.append("")
    n = index.get("n", 0)
    if not rows:
        out.append(f"   not enough community data yet ({n} submission(s); 5+ per metric needed).")
        out.append("   be one of the first: agentburn --submit")
        out.append("")
        return "\n".join(out)
    for r in rows:
        val = f"{r['value']:,}" if r["value"] >= 10 else f"{r['value']:.1%}" if r["value"] <= 1 else str(r["value"])
        med = r["median"]
        meds = f"{med:,}" if isinstance(med, (int, float)) and med >= 10 else (f"{med:.1%}" if isinstance(med, (int, float)) else "–")
        pos = r["worse_than_pct"]
        if pos is None:
            verdict = dim("no quantiles")
        elif pos >= 75:
            verdict = red(f"worse than ~{pos}% of {r['n']}")
        elif pos <= 25:
            verdict = green(f"better than ~{100 - pos}% of {r['n']}")
        else:
            verdict = f"around the middle of {r['n']}"
        out.append(f"   {r['label']:<42} you: {val:>9}   median: {meds:>9}   {verdict}")
    out.append("")
    out.append(dim(f"   index: {index.get('as_of', '?')} · {n} submissions · spend shown only as coarse bands"))
    out.append(dim("   join it (anonymized, you review first): agentburn --submit"))
    out.append("")
    return "\n".join(out)
